- name: mysql config
  hosts: mysql
  become: yes
  vars:
   mysql_root_password: ExpenseApp@1
   login_host: mysql.lakshmangundapu.icu
  tasks:
  - name: install MySQL server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: Get MySQL version with non-default credentials
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: "{{ login_host }}"
    register: mysql_info
   
  - name: printing mysql_info
    ansible.builtin.debug:
     msg: " {{ mysql_info }}"